### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by vr8hub** [hlund05/jules-verne_the-special-correspondent_lovell-coryell-and-company#1]
These are haphazard, as I noted them as I found them. 

- [x] The date line in the telegram in ch. 10 should have the appropriate CSS to format it as the scans.
- [x] We don't remove quotes for a span, since the span has no formatting associated with it, unlike an italic with a language tag. Any that were removed should be put back.
- [x] Since z3998:verse is present, the verse CSS needs to be as well; see [SEMoS 7.5](https://standardebooks.org/manual/1.7.4/single-page#7.5).
- [x] We use z3998:song, not z3998:lyrics; see [SEMoS 7.5.6.1.3](https://standardebooks.org/manual/1.7.4/single-page#7.5.6.1.3).
- [x] The Latin blockquote in ch. 6 should not have italics. The language tag is on the blockquote, and it needs the appropriate CSS to handle the formatting; see [SEMoS 8.2.9.6](https://standardebooks.org/manual/1.7.4/single-page#8.2.9.6).
- [x] Language tags are present on most non-English titles (good! I often forget them), but there are a few where they're mising, e.g. the Voyage en Chine opera, etc.
- [x] Dame Blanche is referring to La dame Blanche, so should be tagged as an opera (and as French).
- [x] Adding italics to non-English words is formatting, so not Editorial. This is true even when changing something from quotes to italics, like a book title, etc.
- [x] The telegrams in the text should be formatted as blockquotes. Since this is formatting it is not considered editorial, but for some reason I have always committed it as editorial. I think either way is fine, just be sure that there is nothing else in the commit, so that if someone (Alex) disagrees, it's easy to change. See the next item.
- [x] The be8e0c2 commit has several types of work in it: formatting a blockquote, adding language tags, and correcting transcription errors; there are many, many other instances of this as well. Those are three different types of work. Further, you have labeled the commit editorial, and fixing transcription errors is _not_ editorial, so the commit would have to be rebased and split into two commits if the editorial was correct. However, as mentioned, formatting is generally not editorial, so instead the commit message should be changed. This is still a rebase, but it's the easiest kind; if you haven't done one before, let me know and I can give you some instructions. You don't need to split the commits this time, but please make a note for the future to only do a single unit of work in a commit. (See the big yellow block at the beginning of the [Step by Step Guide](https://standardebooks.org/contribute/producing-an-ebook-step-by-step.)
- [x] We don't use the z3998:organization tag, and we don't put language tags on proper names; see [SEMoS 8.2.9.2](https://standardebooks.org/manual/1.7.4/single-page#8.2.9.2). These should be removed.
- [x] The continued class is for use outside of a blockquote, not inside of it; see [SEMoS 8.4.2.1](https://standardebooks.org/manual/1.7.4/single-page#8.4.2.1). If there is other formatting to be done within the blockquote, the appropriate CSS selectors should be used to do so. (If all of the telegrams are formatted identically, there are enough of them it is reasonable to create a class.)
- [x] The scans are clearly British spelling (colour, honour, centre, etc.), some of which was apparently changed in the transcription (or a different edition used). Regardless, we don't change British to US spelling or vice-versa as part of our process, so changes like commit 0d971c5 to "Americanize" spellings will need to be reverted. There are others, e.g. commit fed9f888 (which is marked as "modernizing" spelling, but programme is British spelling, so that is not a modernization), commit 548d3c4, and so on. All of them need to be reverted/reversed. The commits to standardize spelling are fine (although given the above I would have changed them to the British spelling, they're fine as is).
- [x] When an entire non-paragraph element is formatted the same, the formatting should generally done via CSS rather than markup. E.g., the blockquote in ch. 13 should be formatted with CSS rather than `<b>`.
- [x] For the book title in ch. 9, the "title" semantic is for chapter titles, not book titles. For book titles which we use the SE vocabulary, as for newspapers, etc.
- [x] Therefore, the actual title portion of that (the first sentence) should be tagged as a book.
- [x] On the same blockquote, breaks (`<br/>`) are generally for breaks within a sentence (excluding poetry). Therefore there should be three `<p>`s in the blockquote.
- [x] None of Madame, Mademoiselle, or Monsieur need language spans, there are no issues with pronunciation of any of them.
- [x] Fixing transcription errors are not editorial, so, e.g., commit 8f88197 should not be marked editorial.
- [x] Arkar is just another name for a urial, so there wouldn't appear to be a reason for it to have a language tag.
- [x] There are tagged words/phrases, e.g. tête-à-tête, au revoir, etc., that are in Merriam-Webster and therefore should not be tagged; see [SEMoS 8.2.9.4](https://standardebooks.org/manual/1.7.4/single-page#8.2.9.4).
- [x] There are taxonomy (e.g. Haloxylon ammodendron) and Latin phrases that are unsemanticated. There should generally not be any unsemanticated italics, although there are rare exceptions; see [SEMoS 8.2](https://standardebooks.org/manual/1.7.4/single-page#8.2).
- [x] The placement of the hyphen in "suddenly" in the blockquote in ch. 19 does not match the scans. It also should be a no-break hyphen; [see SEMOS 8.7.7.6](https://standardebooks.org/manual/1.7.4/single-page#8.7.7.6).
- [x] Commit 8568aae should not be editorial, as again fixing transcription errors are not editorial. Same for commit 53cac40.
- [x] Commit 8834a7b is mixing editorial (changing capitalization) with non-editorial (adding a language tag to a word); that will need to be rebased and split into two commits.
- [x] So is commit 9c88e31. But, the editorial change, changing the line breaks, is unnecessary and should be reverted.
- [x] So is commit e640111; the quotes were added in a separate commit, so changing the position of the comma can't possibly be editorial.
- [x] Commit 27ff0fb is also removing a tag that was added in a previous commit, so again can't be editorial. (And, as noted previously, changing formatting isn't editorial.)
- [x] Commit b82ea51 is either not editorial or is a mixture of editorial and non-editorial. There are no spaces in the scans between the exclamations after luggage van and it's debatable whether there are after Kinko. I think it's safe to just remove the editorial.
- [x] We only use the name vocabulary (surname, etc.) for abbreviations. It's not needed on just regular names (About), and it doesn't apply to Cornaro—he's referring to a book by the author's name; the object isn't a person, but a book. We only tag book titles, though, so no tag is needed there.
- [x] U.S.A. is an abbreviation and should be tagged as such.
- [x] The inscriptions in ch. 28, if left italics, should be tagged individually. But, given SEMoS, and the use of quotes for the same list of phrases in ch. 13, I think they should probably be quoted instead. The commit should be editorial.
- [x] The spans in the ch. 1 blockquote do not appear to be serving any function and should be removed.
- [x] z3998:postal is again used for abbreviations. The blockquote with it can be just a plain blockquote.
- [x] We cut "The End" and similar text at the end of a book. (I thought this was covered in the Step by Step, but I couldn't find it when I looked just now.)
- [x] There are instances of italics being used in the scans instead of quotes for things someone else said, e.g. the last "Wait a bit" in ch. 2, the "thank you, sir" in ch. 3, the "Fragile," et al in ch. 4. This enters into the uncertain realm, i.e. things not explicitly covered by SEMoS. I think it's OK to leave them as italics (on the principle of not making unnecessary changes), but in that case, since they are not emphasis, they should use `<q>` (for inline quotation) rather than `<em>`.
- [x] The emphasis on "Peking" in ch. 26 is small caps in the scans, and so should be `<strong>`, not `<em>`.
- [x] The remaining instances of emphasis were all added contrary to the scans and should be reverted.
- [x] Boy's Own Paper is not a personal name, so should not have that tag in the colophon.
- [x] Any lint errors remaining after everything is finished either need to be corrected, or if they are a false positive, a lint ignore file created for them. [See SEMoS 2.3](https://standardebooks.org/manual/1.7.4/single-page#2.3).

**Comment by vr8hub** [comment]
>1. I understand that `<i>` tags should (almost) always have semantics.  Would that include the examples below, and if so, how would you suggest classifying them?
In Chap 12, the Bon Marché (department store) and Louvre (museum) are italicized.
In Chap 16, Cornaro is italicized in reference to the book authored by Cornaro (you referenced this one in your feedback).
In Chap 18, the Life Travellers Society is italicized as an insurance company. 
>2. In a couple of blockquotes, there are line breaks in the scans that are dictated by the width of the page.  I thought in an ebook format it would be better to remove these where logical, but wanted to confirm if I should leave all those breaks in place to match the scans.
>3. In commit e640111, I removed single quotes from character names (characters referenced from a book/opera).  Is this an editorial change? 

Let's keep things related to the review here, so everything is in one place.
1. None of those should be italicized (I mentioned this above re Cornaro, but I said "tag"; that includes the italic itself). Since it's just formatting I would not consider those editorial, but as always, do them in a commit by themselves so it's easy to change if Alex disagrees.
2. Which specific blockquotes? I can't say without knowing what the blockquote looks like.
3. No, as I said above ("Adding italics to non-English words is formatting, so not Editorial. _This is true even when changing something from quotes to italics, like a book title, etc._").

**Comment by vr8hub** [comment]
Just checking in to see how it's going.

**Comment by hlund05** [comment]
Thanks Vince for checking in.  I've made it through your feedback and the necessary rebasing.  I'm just wanting to do a final proofread, and this week got very busy for me.  I should come back to you in the next 2-3 days when I'm ready for you to take another look.

**Comment by vr8hub** [comment]
No worries, take your time.

**Comment by hlund05** [comment]
I've made it through my proofread, and when you have time, I would be ready for you to take another look at my repo.  Thanks in advance!
